### ISSUE TITLE
refactor : 로그아웃 / 필요 dto 수정 

### ISSUE THREAD

**Issue by singsangssong** [TG-WinG/tgwing.kr#7]
# Title

- title

# TODO

- [ ] 로그아웃 기능 제작
- [ ] dto페이지 필요부분 수정하기
- [ ] 회원 등록시, 곧바로 토큰 발급하고 메인화면으로 가도록 수정
- [ ] 메인페이지에서 프로필이랑 해당 유저 이름 제공하기

# etc
